# explanation #
mylib.f90 uses subroutines.
![structure](img/fig_mymod.png)

## fortran directive ##
f2py reads !f2py directives in fortran
```
subroutine apb(n,a,b,c)
  implicit none
  integer n
  real(8) a(n,n)
  real(8) b(n,n)
  real(8) c(n,n)
  !f2py intent(in) n
  !f2py intent(in) a
  !f2py intent(in) b
  !f2py intent(out) c
```

## python side ##
Then 
```
c = mylib.apb(a,b)
``` 
in python. 

## \_\_doc__##
I recommend to type mylib.apb.\_\_doc__ before writing the code. It shows the interface like
```
c = apb(a,b,[n])

Wrapper for ``apb``.

Parameters
----------
a : input rank-2 array('d') with bounds (n,n)
b : input rank-2 array('d') with bounds (n,n)

Other Parameters
----------------
n : input int, optional
    Default: shape(a,0)

Returns
-------
c : rank-2 array('d') with bounds (n,n)
```
You can see that the variable 'n' is an optional variable in calling inpython. The interface isn't the same as the fortran subroutine definition.

In [1]:
import numpy as np
import numpy as np
import inspect
import mylib

In [2]:
def make_vec():
    n = 4
    m = 3
    a1 = np.array(n)
    a1 = []
    for i in range(n):
       a1.append(i+1)
    a1 = np.array(a1)
    b1 = []
    for j in range(m):
       b1.append(j+1)
    b1 = np.array(b1)
    return a1,b1


def test1():
    print 
    print "subroutine",inspect.currentframe().f_code.co_name
    a1,b1 = make_vec()
    print "a=",a1
    print "b=",b1
    print "apply a*b"
    print mylib.vavbmc.__doc__
    c1 = mylib.vavbmc(a1,b1)
    print "c=",c1
    print 


def make_matrix():
    n = 4
    a1 = np.zeros( (n,n) )
    b1 = np.zeros( (n,n) )
    for i in range(n):
       for j in range(n):
           a1[i,j] = (i+j)*0.1
    for i in range(n):
       for j in range(n):
           b1[i,j] = (i-j)*0.1
    return a1,b1

def test2():
    print 
    print "subroutine",inspect.currentframe().f_code.co_name
    a1,b1 = make_matrix()
    print "a=",a1
    print "b=",b1
    print "apply a+b"
    c1 = mylib.apb(a1,b1)
    print "c1=",c1

def test3():
    print
    print "subroutine",inspect.currentframe().f_code.co_name
    a1,b1 = make_matrix()
    print "a=",a1
    print "b=",b1
    p = 10.0 
    print "apply (a+b)*p, p=",p
    c1 = mylib.apb_p(p, a1,b1)
    print "c1=",c1


if __name__ == "__main__":
    test1()
    test2()
    test3()


subroutine test1
a= [1 2 3 4]
b= [1 2 3]
apply a*b
c = vavbmc(a,b,[n,m])

Wrapper for ``vavbmc``.

Parameters
----------
a : input rank-1 array('d') with bounds (n)
b : input rank-1 array('d') with bounds (m)

Other Parameters
----------------
n : input int, optional
    Default: len(a)
m : input int, optional
    Default: len(b)

Returns
-------
c : rank-2 array('d') with bounds (n,m)

c= [[  1.   2.   3.]
 [  2.   4.   6.]
 [  3.   6.   9.]
 [  4.   8.  12.]]


subroutine test2
a= [[ 0.   0.1  0.2  0.3]
 [ 0.1  0.2  0.3  0.4]
 [ 0.2  0.3  0.4  0.5]
 [ 0.3  0.4  0.5  0.6]]
b= [[ 0.  -0.1 -0.2 -0.3]
 [ 0.1  0.  -0.1 -0.2]
 [ 0.2  0.1  0.  -0.1]
 [ 0.3  0.2  0.1  0. ]]
apply a+b
c1= [[ 0.   0.   0.   0. ]
 [ 0.2  0.2  0.2  0.2]
 [ 0.4  0.4  0.4  0.4]
 [ 0.6  0.6  0.6  0.6]]

subroutine test3
a= [[ 0.   0.1  0.2  0.3]
 [ 0.1  0.2  0.3  0.4]
 [ 0.2  0.3  0.4  0.5]
 [ 0.3  0.4  0.5  0.6]]
b= [[ 0.  -0.1 -0.2 -0.3]
 [ 0.1  0.  -0.1 -0.2]
 [ 0.2  0.1  0.  -0.1]
 [ 0.3  0.2  0.1  0. ]]
apply