# introduction #
myext.f90 uses
fortran module 
and calls external sub module in m_ext.f90.

## f2py accepts global variables in modules.##
 
m_ext.f90 uses global variables in the module.
```
module m_ext
implicit none

integer:: g_n = 3
real(8),allocatable :: g_v(:,:)

contains

subroutine m_ext_init(mode,n)
...
```

## limitation ##

Unfortunately f2py doesn't accept derived types, structure, or classes.


In [1]:
import numpy as np
import myext
import numpy as np
import inspect

def make_vec():
    n = 4
    m = 3
    a1 = np.array(n)
    a1 = []
    for i in range(n):
       a1.append(i+1)
    a1 = np.array(a1)
    b1 = []
    for j in range(m):
       b1.append(j+1)
    b1 = np.array(b1)
    return a1,b1


def test1():
    print 
    print "subroutine",inspect.currentframe().f_code.co_name
    a1,b1 = make_vec()
    print "a=",a1
    print "b=",b1
    print "apply a*b"
    c1 = myext.m_mylib.vavbmc(a1,b1)
    print "c=",c1
    print 


def make_matrix():
    n = 4
    a1 = myext.m_mylib.init("+",n,0.1)
    b1 = myext.m_mylib.init("-",n,0.1)
    return a1,b1

def test2():
    print 
    print "subroutine",inspect.currentframe().f_code.co_name
    a1,b1 = make_matrix()
    print "a=",a1
    print "b=",b1
    print "apply a+b"
    c1 = myext.m_mylib.apb(a1,b1)
    print "c1=",c1

def test3():
    print
    print "subroutine",inspect.currentframe().f_code.co_name
    a1,b1 = make_matrix()
    print "a=",a1
    print "b=",b1
    p = 10.0 
    print "apply (a+b)*p, p=",p
    c1 = myext.m_mylib.apb_p(p, a1,b1)
    print "c1=",c1


if __name__ == "__main__":
    test1()
    test2()
    test3()




subroutine test1
a= [1 2 3 4]
b= [1 2 3]
apply a*b
c= [[  1.   2.   3.]
 [  2.   4.   6.]
 [  3.   6.   9.]
 [  4.   8.  12.]]


subroutine test2
a= [[ 0.2  0.3  0.4  0.5]
 [ 0.3  0.4  0.5  0.6]
 [ 0.4  0.5  0.6  0.7]
 [ 0.5  0.6  0.7  0.8]]
b= [[ 0.  -0.1 -0.2 -0.3]
 [ 0.1  0.  -0.1 -0.2]
 [ 0.2  0.1  0.  -0.1]
 [ 0.3  0.2  0.1  0. ]]
apply a+b
c1= [[ 0.2  0.2  0.2  0.2]
 [ 0.4  0.4  0.4  0.4]
 [ 0.6  0.6  0.6  0.6]
 [ 0.8  0.8  0.8  0.8]]

subroutine test3
a= [[ 0.2  0.3  0.4  0.5]
 [ 0.3  0.4  0.5  0.6]
 [ 0.4  0.5  0.6  0.7]
 [ 0.5  0.6  0.7  0.8]]
b= [[ 0.  -0.1 -0.2 -0.3]
 [ 0.1  0.  -0.1 -0.2]
 [ 0.2  0.1  0.  -0.1]
 [ 0.3  0.2  0.1  0. ]]
apply (a+b)*p, p= 10.0
c1= [[ 20.  30.  40.  50.]
 [ 30.  40.  50.  60.]
 [ 40.  50.  60.  70.]
 [ 50.  60.  70.  80.]]
